/*DELIMITER $$

CREATE TRIGGER before_insert_usuario
BEFORE INSERT ON Usuarios
FOR EACH ROW
BEGIN
    SET NEW.CONTRASEÑA = SHA2(NEW.CONTRASEÑA, 256);
END$$

DELIMITER ;
*/
-- SHOW TRIGGERS;

INSERT INTO Usuarios (ID_USUARIO, CORREO, CONTRASEÑA, PERFIL, ESTATUS, ALTA_REG) VALUES (1, 'uno@ejemplo.com', '1', 'A', '1', NOW());
INSERT INTO Usuarios (ID_USUARIO, CORREO, CONTRASEÑA, PERFIL, ESTATUS, ALTA_REG) VALUES (2, 'dos@ejemplo.com', '2', 'A', '1', NOW());
INSERT INTO Usuarios (ID_USUARIO, CORREO, CONTRASEÑA, PERFIL, ESTATUS, ALTA_REG) VALUES (3, 'tres@ejemplo.com', '3', 'A', '2', NOW());
INSERT INTO Usuarios (ID_USUARIO, CORREO, CONTRASEÑA, PERFIL, ESTATUS, ALTA_REG) VALUES (4, 'cuatro@ejemplo.com', '4', 'B', '1', NOW());
INSERT INTO Usuarios (ID_USUARIO, CORREO, CONTRASEÑA, PERFIL, ESTATUS, ALTA_REG) VALUES (5, 'cinco@ejemplo.com', '5', 'B', '1', NOW());
